language: python
python:
- '3.3'
- '3.4'
- nightly
matrix:
  allow_failures:
  - python: nightly
cache:
  directory:
  - "$HOME/.cache/pip"
install:
- pip install -r test_requirements.txt
- pip install .
before_script:
- psql -U postgres -c "DROP DATABASE IF EXISTS slamon;"
- psql -U postgres -c "DROP DATABASE IF EXISTS slamon_tests;"
- psql -U postgres -c "DROP USER IF EXISTS afm;"
- psql -U postgres -c "CREATE DATABASE slamon;"
- psql -U postgres -c "CREATE DATABASE slamon_tests;"
- psql -U postgres -c "CREATE USER afm WITH PASSWORD 'changeme';"
- psql -U postgres -c "GRANT ALL ON DATABASE slamon TO afm;"
- psql -U postgres -c "GRANT ALL ON DATABASE slamon_tests TO afm;"
- python ./slamon_afm/admin.py --create-tables
script:
- nosetests --with-coverage --cover-erase --cover-package=slamon_afm
notifications:
  webhooks:
    urls:
    - secure: feEKRGM5pwxP6FenUYuGRNgxXj4O5vQfSsm8x3Zmv//pau4CEnKJ10R58Knu4aHdNuRab5U9OZF7vtcdCOtxdUUWULmCj5XFgUOdcyXpgkdMN9zkcV54bTU2DdwRqXX19h1Uas+bTxVvJLQy+OWX9BaGXvCcHKXvhh5OmcRoLmoHcpizrnMkahAh7uaOuhqgSVV/vSRv/RLYACrIbyT40b/CXeHenraJhLZMXBYtgTkgXQaxIjXHEZp3bcuYM2ErQCoRxvT32RO+qBtWthAWhpzFATBLKIYUoyJmPUvfFuD5iGOdPEvSm7Xkwh2efLFNsRqwMJwPFg5+tCjFo/Ln2zgZ4PwNHA9BE9H4W7RderqSQlMz6N/uQDeXJJiFWB1IWZUVMuPBuM89sfALvPmlxD4jUbokJwgJBkGiX7CdNM7kZKzMytqAGBtemgwWGBSd3AY9YA/8mTR7mY18hWxAjfrAB8v7U9/BjvZycgXGO6kmAGn3gWJF7JTxwl/Awr/TrOPt/1zT0jyAc8x5YWLoiUhiA/PHcM4TmNm877jsCRROxUJgGvHlOFYKjKAYSay6Uj7CBS2OLaepclReRRXKokgdi6SZrwbBkwSAwzZ7aRoecZ0IZ2LGa0752dlHIK/ZaFd0eWlFYWBbL8n2GawlI7qp4bBzfs5T0gaSWgO8mYQ=
  "    on_success": change
  "    on_failure": always
  "    on_start": false
after_success:
- coveralls
deploy:
  provider: pypi
  user: slamon
  password:
    secure: HrPCBzDVOnHYZQkP9OcHkOPLwqwKfvv/+N3Np9vcBpIpOSpzarZ+ihN9bpAsud7MUy8m0R1M8b9yXPySYaWK4PfjLXRbcyi4Q3WLDXECar2dpUqKDrd/9dIGEiLGy1RgRXx/fizOew9K+5UOtVCYxITzj5x9Nesfkd1hynEbEZlmr1ZfCgK4m1LloirrRN/YrxkC6/kP2BptpR4itTnsrwnj0xDoIYqKPKZXpv6DpfuV+Pkw2qLt93ArIoaV+os/r+DJAIJAcwrYXmd2ySE62+/x0hkk+9ic8G54VoOum8BahBEQV9tZyBV1Olt4jQC3ZI5LwdAQl8SkpSCrpu1o9gN/JlyLWRy/3/oiy4JymogKTwZ0sCOMB55ZagWrHMcoKy7KMBJzN5GrcJPmXdVCYsKNYs/0r3/aBBNgZFqzZfGkFOb6enJLFy4STO7mvvpUwLC7xcJrn3pZFhZQD5Bv984qtsBpZ9bKkVH0gly8sASvG61I29bsIAkIdbiYzLKWsxeq3S0LyGWQa2ftN16pIYlOK+K6Pgc2STYg08nktlbN+zIurhWi5ZdAqPGnPK2MViERHbC3bDCKPhkTEjq6X4Hra2mjTJxjUbotpByq21PZlQ7CX+NFLqdMRVwgJTR8oX8BUVsBoZZ+zjDmOtZE6VXKF1S+9Z0TVqg8GXfLkZI=
  on:
    tags: true
    branch: master
    repo: SLAMon/slamon-agent-fleet-manager
